"""Add task_id to audio_files

Revision ID: 05527f0dd8c8
Revises: 5480e33db06c
Create Date: 2025-11-09 20:24:11.485969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05527f0dd8c8'
down_revision = '5480e33db06c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'task_id')
    # ### end Alembic commands ###
